/** Search tags and browse groups. Not stored on the skill row. */

type NicheGroup = "care" | "money" | "home" | "language" | "games" | "craft" | "future" | "mind";

const META: Record<string, { group: NicheGroup; tags: string }> = {
  "full-stack-web-dev": { group: "future", tags: "react javascript coding database web programming" },
  "art-painting": { group: "craft", tags: "paint drawing canvas color sketch" },
  photography: { group: "craft", tags: "camera photo light framing lens" },
  "music-production": { group: "craft", tags: "mixing daw audio recording beat" },
  "content-creation": { group: "craft", tags: "youtube publishing video audience creator" },
  "self-grooming": { group: "care", tags: "hair skin grooming appearance" },
  animation: { group: "craft", tags: "motion drawing timing cartoon" },
  "travel-vlogging": { group: "craft", tags: "travel video youtube trip filming" },
  "story-writing": { group: "craft", tags: "fiction novel plot character writing" },
  "iot-robot-automation": { group: "future", tags: "sensors robots hardware arduino automation" },
  cybersecurity: { group: "future", tags: "hacking passwords phishing security accounts" },
  "data-analysis": { group: "future", tags: "spreadsheet charts statistics data" },
  "machine-learning": { group: "future", tags: "ai model training prediction" },
  "ui-design": { group: "craft", tags: "interface layout buttons screens design" },
  "ux-research": { group: "craft", tags: "usability interviews users testing" },
  "graphic-design": { group: "craft", tags: "poster branding layout visual" },
  "digital-marketing": { group: "future", tags: "ads audience social campaign" },
  seo: { group: "future", tags: "search google ranking keywords" },
  "product-management": { group: "future", tags: "roadmap product users priority" },
  "project-management": { group: "future", tags: "deadline planning team schedule" },
  "cloud-fundamentals": { group: "future", tags: "servers aws hosting infrastructure" },
  devops: { group: "future", tags: "deploy ci cd release pipeline" },
  "mobile-development": { group: "future", tags: "ios android app phone" },
  copywriting: { group: "craft", tags: "ads headlines persuasion writing" },
  sales: { group: "money", tags: "selling offer customers closing" },
  "first-aid": { group: "care", tags: "cpr bleeding choking emergency ambulance" },
  "food-safety": { group: "care", tags: "hygiene contamination temperature kitchen" },
  "home-repair": { group: "home", tags: "house fix tools drywall" },
  "auto-maintenance": { group: "home", tags: "car oil tires brakes vehicle" },
  "personal-finance": { group: "money", tags: "budget debt saving money bills" },
  bookkeeping: { group: "money", tags: "ledger receipts accounts invoices" },
  "emergency-preparedness": { group: "home", tags: "disaster go-bag power outage water" },
  "sign-language": { group: "language", tags: "asl deaf signing visual" },
  "statistical-literacy": { group: "mind", tags: "average sample chart probability" },
  "information-literacy": { group: "mind", tags: "sources rumor fact-check news" },
  "digital-privacy": { group: "future", tags: "passwords tracking permissions surveillance" },
  accessibility: { group: "future", tags: "screen-reader captions keyboard a11y" },
  welding: { group: "home", tags: "metal torch joints fabrication" },
  carpentry: { group: "home", tags: "wood saw furniture build" },
  sewing: { group: "craft", tags: "fabric stitch clothes pattern" },
  gardening: { group: "home", tags: "plants soil yard vegetables" },
  nutrition: { group: "care", tags: "diet meals food protein" },
  "motion-design": { group: "craft", tags: "animation after-effects motion graphics" },
  "3d-modeling": { group: "craft", tags: "blender mesh sculpture cad" },
  illustration: { group: "craft", tags: "drawing ink picture" },
  "sound-design": { group: "craft", tags: "audio foley noise film" },
  cinematography: { group: "craft", tags: "camera film lighting shot" },
  "film-editing": { group: "craft", tags: "cuts premiere timeline video" },
  pottery: { group: "craft", tags: "clay ceramic wheel kiln" },
  "technical-writing": { group: "craft", tags: "docs manual instructions writing" },
  translation: { group: "language", tags: "interpreter bilingual meaning" },
  "research-methods": { group: "mind", tags: "study evidence method science" },
  "ai-literacy": { group: "future", tags: "chatgpt model hallucination prompt" },
  "embedded-systems": { group: "future", tags: "microcontroller firmware hardware" },
  "climate-literacy": { group: "future", tags: "weather carbon energy climate" },
  "public-speaking": { group: "mind", tags: "speech presentation talk stage" },
  spreadsheets: { group: "money", tags: "excel formulas sheets numbers" },
  cooking: { group: "home", tags: "recipes kitchen meals heat" },
  "critical-thinking": { group: "mind", tags: "logic argument bias reasoning" },
  "game-development": { group: "future", tags: "games unity design programming" },
  badminton: { group: "games", tags: "racket shuttlecock court" },
  squash: { group: "games", tags: "racket court rally" },
  tennis: { group: "games", tags: "racket serve court" },
  "table-tennis": { group: "games", tags: "ping-pong paddle spin" },
  "eight-ball": { group: "games", tags: "pool billiards cue table" },
  chess: { group: "games", tags: "openings tactics checkmate board" },
  golf: { group: "games", tags: "swing putt range club" },
  pickleball: { group: "games", tags: "paddle dink court kitchen" },
  darts: { group: "games", tags: "checkout board bullseye" },
  bowling: { group: "games", tags: "lane pins spare strike" },
  snooker: { group: "games", tags: "cue billiards table pots" },
  carrom: { group: "games", tags: "striker queen board coins" },
  "digital-legacy": { group: "mind", tags: "passwords death accounts memorial" },
  caregiving: { group: "care", tags: "elder care disability daily-living" },
  "dementia-communication": { group: "care", tags: "alzheimer memory aging talking" },
  "grief-literacy": { group: "care", tags: "mourning loss funeral condolence" },
  "estate-basics": { group: "money", tags: "will probate death inheritance" },
  "scam-recognition": { group: "money", tags: "phishing fraud otp spam call" },
  "deepfake-literacy": { group: "future", tags: "fake-video ai voice generated" },
  "bureaucracy-navigation": { group: "mind", tags: "forms government office appeal paperwork" },
  "insurance-literacy": { group: "money", tags: "policy claim premium coverage" },
  "household-administration": { group: "home", tags: "papers renewals bills records" },
  "attention-practice": { group: "mind", tags: "focus distraction deep-work" },
  "deliberate-practice": { group: "mind", tags: "practice feedback mastery drill" },
  facilitation: { group: "mind", tags: "meeting agenda decision workshop" },
  "de-escalation": { group: "mind", tags: "conflict anger calm argument" },
  "oral-history": { group: "mind", tags: "interview elder story recording" },
  "family-archive": { group: "mind", tags: "photos letters genealogy memory" },
  "plain-language": { group: "mind", tags: "rewrite clarity forms official" },
  "clothing-care": { group: "home", tags: "laundry wash wardrobe clothes" },
  mending: { group: "home", tags: "patch sew repair hole" },
  "seed-saving": { group: "home", tags: "seeds harvest garden heirloom" },
  foraging: { group: "home", tags: "wild plants mushrooms identify" },
  "taste-training": { group: "care", tags: "palate flavor tasting food" },
  "passive-cooling": { group: "home", tags: "heat shade ventilation summer" },
  "supply-chain-literacy": { group: "future", tags: "manufacturing imports origin goods" },
  "civic-budget": { group: "mind", tags: "town taxes spending council" },
  "library-research": { group: "mind", tags: "library books archives reference" },
  "health-literacy": { group: "care", tags: "doctor results label diagnosis" },
  apprenticeship: { group: "mind", tags: "mentor trade learning on-the-job" },
  spanish: { group: "language", tags: "espanol language conversation" },
  japanese: { group: "language", tags: "nihongo kana kanji language" },
  korean: { group: "language", tags: "hangul language conversation" },
  english: { group: "language", tags: "grammar writing esl clarity sentences" },
  sleep: { group: "care", tags: "insomnia rest bedtime circadian night" },
  "tax-basics": { group: "money", tags: "irs filing deductions return taxes" },
  "medication-literacy": { group: "care", tags: "prescription dose pharmacy pills side-effects" },
  renting: { group: "home", tags: "lease landlord deposit tenant apartment" },
  guitar: { group: "craft", tags: "chords strings music instrument" },
  piano: { group: "craft", tags: "keys music instrument" },
  drums: { group: "craft", tags: "rhythm beats music percussion" },
  singing: { group: "craft", tags: "voice pitch music vocal" },
  "music-theory": { group: "craft", tags: "chords keys intervals harmony" },
  songwriting: { group: "craft", tags: "lyrics melody chorus music" },
  acting: { group: "craft", tags: "theatre scene performance drama" },
  poetry: { group: "craft", tags: "poem verse writing" },
  journalism: { group: "craft", tags: "reporting news interview story" },
  podcasting: { group: "craft", tags: "audio show microphone recording" },
  baking: { group: "home", tags: "oven cake pastry dessert" },
  "bread-making": { group: "home", tags: "sourdough loaf yeast flour" },
  coffee: { group: "home", tags: "espresso brew beans cafe" },
  beekeeping: { group: "home", tags: "hive honey bees colony" },
  "dog-training": { group: "home", tags: "puppy cues obedience pet" },
  birdwatching: { group: "mind", tags: "birds binoculars nature" },
  astronomy: { group: "mind", tags: "stars telescope night-sky planets" },
  philosophy: { group: "mind", tags: "ethics argument ideas" },
  psychology: { group: "mind", tags: "behavior study mind people" },
  economics: { group: "money", tags: "markets prices incentives trade" },
  mathematics: { group: "mind", tags: "math proof numbers algebra" },
  physics: { group: "mind", tags: "motion force energy science" },
  negotiation: { group: "mind", tags: "deal agreement salary bargain" },
  mindfulness: { group: "mind", tags: "meditation attention calm breath" },
  investing: { group: "money", tags: "stocks index funds risk portfolio" },
  entrepreneurship: { group: "money", tags: "startup business customer offer" },
  python: { group: "future", tags: "programming code scripting" },
  sql: { group: "future", tags: "database query tables" },
  typography: { group: "craft", tags: "fonts type lettering layout" },
  "interior-design": { group: "home", tags: "room furniture layout space" },
  calligraphy: { group: "craft", tags: "lettering pen handwriting" },
  knitting: { group: "craft", tags: "yarn needles wool" },
  "3d-printing": { group: "future", tags: "printer slicer filament maker" },
  "electronics-repair": { group: "home", tags: "circuit solder device fix" },
  plumbing: { group: "home", tags: "leak pipes water shutoff" },
  sailing: { group: "home", tags: "boat wind knots water" },
  fishing: { group: "home", tags: "tackle cast water angling" },
  "floral-design": { group: "craft", tags: "flowers bouquet arrangement" },
  "urban-farming": { group: "home", tags: "balcony garden containers food" },
  "renewable-energy": { group: "future", tags: "solar wind panels electricity" },
  parenting: { group: "care", tags: "children baby routines family" },
  screenwriting: { group: "craft", tags: "script film dialogue scene" },
};

export function nicheMeta(slug: string): { group: NicheGroup; tags: string[] } {
  const row = META[slug];
  if (!row) return { group: "mind", tags: [] };
  return { group: row.group, tags: row.tags.split(" ") };
}
