/** Niches beyond the five original skills. Coming soon until a path is built. */
export function slugFromName(name: string) {
  return name
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

export const EXTRA_NICHES: { slug: string; name: string; description: string }[] = [
  { slug: "self-grooming", name: "Self-Grooming", description: "Hair, skin, and the habits that make day-to-day presentation deliberate." },
  { slug: "animation", name: "Animation", description: "Movement, timing, and how a still drawing becomes a scene." },
  { slug: "travel-vlogging", name: "Travel Vlogging", description: "Planning, filming, and editing a trip so the story is watchable." },
  { slug: "story-writing", name: "Story Writing", description: "Plot, character, and revision for short and long fiction." },
  { slug: "iot-robot-automation", name: "IoT & Robot Automation", description: "Sensors, controllers, and the software that moves a physical machine." },
  { slug: "cybersecurity", name: "Cybersecurity", description: "How accounts, networks, and software are attacked and defended." },
  { slug: "data-analysis", name: "Data Analysis", description: "Cleaning data, finding a pattern, and saying what it does not prove." },
  { slug: "machine-learning", name: "Machine Learning", description: "Training a model, measuring it, and knowing when it is guessing." },
  { slug: "ui-design", name: "UI Design", description: "Layout, type, and controls people can actually use." },
  { slug: "ux-research", name: "UX Research", description: "Watching how people use a product and what to change because of it." },
  { slug: "graphic-design", name: "Graphic Design", description: "Composition, hierarchy, and type for posters, brands, and screens." },
  { slug: "digital-marketing", name: "Digital Marketing", description: "How a message finds an audience without pretending every click is a sale." },
  { slug: "seo", name: "SEO", description: "How search engines read a page and what a writer can honestly improve." },
  { slug: "product-management", name: "Product Management", description: "Choosing what to build, for whom, and what to leave out." },
  { slug: "project-management", name: "Project Management", description: "Scope, sequence, and how a group finishes the work it promised." },
  { slug: "cloud-fundamentals", name: "Cloud Fundamentals", description: "What runs on someone else's servers, and how access, cost, and failure work." },
  { slug: "devops", name: "DevOps", description: "Build, test, and release so a change can ship without a scramble." },
  { slug: "mobile-development", name: "Mobile Development", description: "Apps that fit a phone: layout, offline use, and the platform rules." },
  { slug: "copywriting", name: "Copywriting", description: "Writing that helps a person decide, without hiding the tradeoff." },
  { slug: "sales", name: "Sales", description: "Listening for a real need and making an offer someone can refuse." },
  { slug: "first-aid", name: "First Aid", description: "What to do in the first minutes of bleeding, choking, or a collapse." },
  { slug: "food-safety", name: "Food Safety", description: "Temperature, contamination, and storage that keep a meal from making people sick." },
  { slug: "home-repair", name: "Home Repair", description: "The small fixes in a house, and the ones that need a licensed tradesperson." },
  { slug: "auto-maintenance", name: "Auto Maintenance", description: "Fluids, tires, brakes, and the checks that prevent a roadside failure." },
  { slug: "personal-finance", name: "Personal Finance", description: "Spending, debt, and saving in an order that survives a bad month." },
  { slug: "bookkeeping", name: "Bookkeeping", description: "Recording what came in and what went out so the numbers can be trusted." },
  { slug: "emergency-preparedness", name: "Emergency Preparedness", description: "Water, power, and a plan for the first days after a local disaster." },
  { slug: "sign-language", name: "Sign Language", description: "A visual language, practiced as a language and not as a party trick." },
  { slug: "statistical-literacy", name: "Statistical Literacy", description: "Averages, samples, and the claims a chart is not allowed to make." },
  { slug: "information-literacy", name: "Information Literacy", description: "How to tell a source, a rumor, and an ad apart." },
  { slug: "digital-privacy", name: "Digital Privacy", description: "Accounts, permissions, and what a device collects without being asked twice." },
  { slug: "accessibility", name: "Accessibility", description: "Building so people who use a keyboard, a reader, or captions are not locked out." },
  { slug: "welding", name: "Welding", description: "Joints, heat, and the safety gear that belongs on before the arc." },
  { slug: "carpentry", name: "Carpentry", description: "Measure, cut, and join wood so the piece stays square." },
  { slug: "sewing", name: "Sewing", description: "Fabric, pattern, and a machine stitch that holds." },
  { slug: "gardening", name: "Gardening", description: "Soil, water, and seasons for food and plants in a real yard." },
  { slug: "nutrition", name: "Nutrition", description: "What a meal needs to do, past the label on the box." },
  { slug: "motion-design", name: "Motion Design", description: "Type and shape that move with a reason, not a preset." },
  { slug: "3d-modeling", name: "3D Modeling", description: "Form, topology, and a model that can be lit or printed." },
  { slug: "illustration", name: "Illustration", description: "Drawing an idea so it reads at a glance." },
  { slug: "sound-design", name: "Sound Design", description: "Noise, music, and silence chosen for a scene." },
  { slug: "cinematography", name: "Cinematography", description: "Light, lens, and frame so a shot says where to look." },
  { slug: "film-editing", name: "Film Editing", description: "Cuts, pace, and the version of a scene the audience should see." },
  { slug: "pottery", name: "Pottery", description: "Clay, centering, and a firing that does not crack the piece." },
  { slug: "technical-writing", name: "Technical Writing", description: "Instructions a stranger can follow without guessing." },
  { slug: "translation", name: "Translation", description: "Moving meaning between languages, including what should not be literal." },
  { slug: "research-methods", name: "Research Methods", description: "A question, a method, and a result that stays inside the evidence." },
  { slug: "ai-literacy", name: "AI Literacy", description: "What a model can draft, what it invents, and what a person still has to check." },
  { slug: "embedded-systems", name: "Embedded Systems", description: "Software that runs on a small device with limited memory and a real clock." },
  { slug: "climate-literacy", name: "Climate Literacy", description: "Energy, weather, and the difference between a trend and a single hot day." },
  { slug: "public-speaking", name: "Public Speaking", description: "A talk with a point, a structure, and a pace people can follow." },
  { slug: "spreadsheets", name: "Spreadsheets", description: "Cells, formulas, and a sheet someone else can audit." },
  { slug: "cooking", name: "Cooking", description: "Heat, salt, and a meal that finishes at the same time." },
  { slug: "critical-thinking", name: "Critical Thinking", description: "An argument's claim, its evidence, and the step that does not follow." },
  { slug: "game-development", name: "Game Development", description: "Rules, feedback, and a loop a player wants to try again." },
  { slug: "badminton", name: "Badminton", description: "Clears, drops, and footwork you can drill with one partner and a court." },
  { slug: "squash", name: "Squash", description: "The T, the boast, and how to keep a rally going in a small court." },
  { slug: "tennis", name: "Tennis", description: "Serve, groundstrokes, and match play you can practice on a public court." },
  { slug: "table-tennis", name: "Table Tennis", description: "Spin, placement, and the short game on a table you can find in a club or a hall." },
  { slug: "eight-ball", name: "8-Ball Pool", description: "Cue action, angles, and how to clear your group before the 8-ball." },
  { slug: "chess", name: "Chess", description: "Openings, tactics, and endgames you can study and play the same day." },
  { slug: "golf", name: "Golf", description: "Grip, setup, and a short game you can practice at a range." },
  { slug: "pickleball", name: "Pickleball", description: "The kitchen, the dink, and a rally you can start on a public court." },
  { slug: "darts", name: "Darts", description: "Stance, release, and the checkout math of a standard board." },
  { slug: "bowling", name: "Bowling", description: "Approach, release, and how to read a lane from the first frame." },
  { slug: "snooker", name: "Snooker", description: "Cue ball control and the long pots a full-size table rewards." },
  { slug: "carrom", name: "Carrom", description: "The flick, the queen, and how to clear your coins on a board at home." },
  { slug: "digital-legacy", name: "Digital Legacy", description: "What should happen to accounts, photos, and passwords when someone is gone." },
  { slug: "caregiving", name: "Caregiving", description: "The daily work of looking after a person who can no longer do it alone." },
  { slug: "dementia-communication", name: "Dementia Communication", description: "How to talk with someone whose memory is changing, without correcting them into a fight." },
  { slug: "grief-literacy", name: "Grief Literacy", description: "What to say, what to do, and what to leave alone when a person is mourning." },
  { slug: "estate-basics", name: "Estate Basics", description: "A will, the papers, and who is allowed to act when someone dies." },
  { slug: "scam-recognition", name: "Scam Recognition", description: "The patterns in a message, a call, or a payment ask that mean stop." },
  { slug: "deepfake-literacy", name: "Deepfake Literacy", description: "How to tell a generated face or voice from a real recording before you share it." },
  { slug: "bureaucracy-navigation", name: "Bureaucracy Navigation", description: "Forms, offices, and the appeal path when an institution says no." },
  { slug: "insurance-literacy", name: "Insurance Literacy", description: "What a policy actually pays, and the words that decide a claim." },
  { slug: "household-administration", name: "Household Administration", description: "The papers, renewals, and records that keep a home from becoming a pile of surprises." },
  { slug: "attention-practice", name: "Attention Practice", description: "A way to stay with one task long enough to finish it." },
  { slug: "deliberate-practice", name: "Deliberate Practice", description: "How to practice any skill so the next attempt is harder in the right place." },
  { slug: "facilitation", name: "Facilitation", description: "How to run a meeting so the group leaves with a decision, not another date." },
  { slug: "de-escalation", name: "De-escalation", description: "Voice, distance, and the words that bring a tense moment down." },
  { slug: "oral-history", name: "Oral History", description: "How to interview an elder so the story survives the telling." },
  { slug: "family-archive", name: "Family Archive", description: "How to keep photos, letters, and names so the next person can find them." },
  { slug: "plain-language", name: "Plain Language", description: "How to rewrite an official sentence so a stranger can act on it." },
  { slug: "clothing-care", name: "Clothing Care", description: "Wash, store, and repair so a garment lasts longer than a season." },
  { slug: "mending", name: "Mending", description: "A needle, a patch, and a hole that does not come back next week." },
  { slug: "seed-saving", name: "Seed Saving", description: "How to keep seed from this harvest so next season does not start at a shop." },
  { slug: "foraging", name: "Foraging", description: "How to identify a local plant, and the rule that says leave it when you are not sure." },
  { slug: "taste-training", name: "Taste Training", description: "How to name what you taste so cooking and buying stop being guesses." },
  { slug: "passive-cooling", name: "Passive Cooling", description: "Shade, airflow, and the habits that keep a room livable without more machines." },
  { slug: "supply-chain-literacy", name: "Supply Chain Literacy", description: "Where a shirt or a phone actually comes from, and what that hides." },
  { slug: "civic-budget", name: "Civic Budget", description: "How to read what a town spends, and who to ask when a line does not make sense." },
  { slug: "library-research", name: "Library Research", description: "How to use a public library to answer a question a search box will not." },
  { slug: "health-literacy", name: "Health Literacy", description: "How to read a result, a label, and the moment when you need a clinician." },
  { slug: "apprenticeship", name: "Apprenticeship", description: "How to learn beside someone who already does the work, and what to practice between visits." },
  { slug: "spanish", name: "Spanish", description: "Sound, everyday sentences, and the practice that makes them come out without translating." },
  { slug: "japanese", name: "Japanese", description: "Kana, basic grammar, and the phrases a daily drill actually sticks." },
  { slug: "mandarin", name: "Mandarin", description: "Tones, characters, and a small set of sentences you can say out loud." },
  { slug: "french", name: "French", description: "Pronunciation, the present tense, and conversation you can rehearse every day." },
  { slug: "korean", name: "Korean", description: "Hangul, particles, and the polite speech a beginner needs first." },
  { slug: "german", name: "German", description: "Cases, word order, and the sentences a short daily lesson can build." },
  { slug: "arabic", name: "Arabic", description: "The script, the sounds, and a starter vocabulary you can read and say." },
  { slug: "hindi", name: "Hindi", description: "Devanagari, everyday speech, and the patterns a conversation keeps using." },
  { slug: "guitar", name: "Guitar", description: "Chords, strumming, and a song you can play slowly all the way through." },
  { slug: "piano", name: "Piano", description: "Hands, reading, and a piece short enough to finish." },
  { slug: "drums", name: "Drums", description: "Time, the basic beats, and how a fill fits inside a bar." },
  { slug: "singing", name: "Singing", description: "Breath, pitch, and a song you can stay in tune on." },
  { slug: "music-theory", name: "Music Theory", description: "Intervals, keys, and why a chord progression moves the way it does." },
  { slug: "songwriting", name: "Songwriting", description: "A lyric, a melody, and a structure that reaches a chorus on purpose." },
  { slug: "acting", name: "Acting", description: "Objective, listening, and a scene you can rehearse with another person." },
  { slug: "poetry", name: "Poetry", description: "Line, image, and revision until the poem says one clear thing." },
  { slug: "journalism", name: "Journalism", description: "A question, the sources, and a story that stays inside what they said." },
  { slug: "podcasting", name: "Podcasting", description: "A show format, a clean recording, and an edit people can follow." },
  { slug: "baking", name: "Baking", description: "Ratios, heat, and a bake that finishes because the method was followed." },
  { slug: "bread-making", name: "Bread Making", description: "Flour, fermentation, and a loaf with a crumb you can explain." },
  { slug: "coffee", name: "Coffee", description: "Grind, water, and a cup you can repeat from the same beans." },
  { slug: "beekeeping", name: "Beekeeping", description: "The hive, the season, and the checks that keep a colony healthy." },
  { slug: "dog-training", name: "Dog Training", description: "Cues, rewards, and the short sessions a dog can actually learn from." },
  { slug: "birdwatching", name: "Birdwatching", description: "Shape, call, and habitat so a bird in the field has a name." },
  { slug: "astronomy", name: "Astronomy", description: "The night sky, a few constellations, and what a small telescope can show." },
  { slug: "philosophy", name: "Philosophy", description: "An argument, its assumptions, and the question it does not answer." },
  { slug: "psychology", name: "Psychology", description: "How a study is designed, and what a result is allowed to claim about people." },
  { slug: "economics", name: "Economics", description: "Incentives, tradeoffs, and the difference between a price and a cost." },
  { slug: "mathematics", name: "Mathematics", description: "Number, proof, and the problems that get easier once the definition is clear." },
  { slug: "physics", name: "Physics", description: "Motion, force, and a model that predicts what happens next." },
  { slug: "negotiation", name: "Negotiation", description: "Interests, options, and an agreement both sides can live with." },
  { slug: "mindfulness", name: "Mindfulness", description: "Attention, a short sit, and the habit of noticing before you react." },
  { slug: "investing", name: "Investing", description: "Risk, cost, and a plan that does not depend on a tip." },
  { slug: "entrepreneurship", name: "Entrepreneurship", description: "A customer, an offer, and the numbers that say whether it can continue." },
  { slug: "python", name: "Python", description: "Syntax, data, and a small program that does one job correctly." },
  { slug: "sql", name: "SQL", description: "Tables, queries, and an answer you can check against the rows." },
  { slug: "typography", name: "Typography", description: "Type choice, spacing, and a page that is easy to read." },
  { slug: "interior-design", name: "Interior Design", description: "Light, scale, and a room arranged for how people actually use it." },
  { slug: "calligraphy", name: "Calligraphy", description: "A nib, a hand, and letters that stay consistent down the page." },
  { slug: "knitting", name: "Knitting", description: "Cast on, the knit stitch, and a piece that comes out the size you planned." },
  { slug: "3d-printing", name: "3D Printing", description: "A model, the slicer, and a print that finishes without a warp." },
  { slug: "electronics-repair", name: "Electronics Repair", description: "Diagnosis, safe power, and the fix that belongs before you replace the whole device." },
  { slug: "plumbing", name: "Plumbing", description: "Leaks, shutoffs, and the repairs a homeowner can do before calling a plumber." },
  { slug: "sailing", name: "Sailing", description: "Wind, points of sail, and the knots a small boat requires." },
  { slug: "fishing", name: "Fishing", description: "Tackle, water, and the local rules that come before the first cast." },
  { slug: "floral-design", name: "Floral Design", description: "Stem, color, and an arrangement that holds its shape." },
  { slug: "urban-farming", name: "Urban Farming", description: "Soil, containers, and food you can grow in a small outdoor space." },
  { slug: "renewable-energy", name: "Renewable Energy", description: "Sun, wind, and how a home system is sized before it is installed." },
  { slug: "parenting", name: "Parenting", description: "Sleep, boundaries, and the routines that make a hard day smaller." },
  { slug: "screenwriting", name: "Screenwriting", description: "Scene, conflict, and a script someone could shoot." },
];
