/**
 * Question bank for the career-fit test. Generated from the published sources, word for word. Do not edit by hand.
 *
 * IPIP-NEO-120: Johnson, J. A. (2014). Measuring thirty facets of the Five Factor Model with a 120-item public domain
 * inventory. Journal of Research in Personality, 51, 78-89. Table 1 (items, facets, keying). Public domain (ipip.ori.org).
 *
 * O*NET Interest Profiler Short Form: U.S. Department of Labor, Employment and Training Administration. 60 items in the
 * order of presentation (Rounds, Su, Lewis, & Rivkin, 2010, Appendix A), with the two items revised in the 2018 web and
 * paper versions (Rounds et al., 2018). Licensed under CC BY 4.0.
 */

export type Domain = "N" | "E" | "O" | "A" | "C";
export type Area = "R" | "I" | "A" | "S" | "E" | "C";

/** `keyed: "-"` items are reverse-scored (6 minus the answer). */
export type IpipItem = { n: number; facet: string; keyed: "+" | "-"; text: string };
export type OnetItem = { n: number; area: Area; text: string };

export const IPIP_ITEMS: readonly IpipItem[] = [
  { n: 1, facet: "N1", keyed: "+", text: "Worry about things" },
  { n: 2, facet: "E1", keyed: "+", text: "Make friends easily" },
  { n: 3, facet: "O1", keyed: "+", text: "Have a vivid imagination" },
  { n: 4, facet: "A1", keyed: "+", text: "Trust others" },
  { n: 5, facet: "C1", keyed: "+", text: "Complete tasks successfully" },
  { n: 6, facet: "N2", keyed: "+", text: "Get angry easily" },
  { n: 7, facet: "E2", keyed: "+", text: "Love large parties" },
  { n: 8, facet: "O2", keyed: "+", text: "Believe in the importance of art" },
  { n: 9, facet: "A2", keyed: "-", text: "Use others for my own ends" },
  { n: 10, facet: "C2", keyed: "+", text: "Like to tidy up" },
  { n: 11, facet: "N3", keyed: "+", text: "Often feel blue" },
  { n: 12, facet: "E3", keyed: "+", text: "Take charge" },
  { n: 13, facet: "O3", keyed: "+", text: "Experience my emotions intensely" },
  { n: 14, facet: "A3", keyed: "+", text: "Love to help others" },
  { n: 15, facet: "C3", keyed: "+", text: "Keep my promises" },
  { n: 16, facet: "N4", keyed: "+", text: "Find it difficult to approach others" },
  { n: 17, facet: "E4", keyed: "+", text: "Am always busy" },
  { n: 18, facet: "O4", keyed: "+", text: "Prefer variety to routine" },
  { n: 19, facet: "A4", keyed: "-", text: "Love a good fight" },
  { n: 20, facet: "C4", keyed: "+", text: "Work hard" },
  { n: 21, facet: "N5", keyed: "+", text: "Go on binges" },
  { n: 22, facet: "E5", keyed: "+", text: "Love excitement" },
  { n: 23, facet: "O5", keyed: "+", text: "Love to read challenging material" },
  { n: 24, facet: "A5", keyed: "-", text: "Believe that I am better than others" },
  { n: 25, facet: "C5", keyed: "+", text: "Am always prepared" },
  { n: 26, facet: "N6", keyed: "+", text: "Panic easily" },
  { n: 27, facet: "E6", keyed: "+", text: "Radiate joy" },
  { n: 28, facet: "O6", keyed: "+", text: "Tend to vote for liberal political candidates" },
  { n: 29, facet: "A6", keyed: "+", text: "Sympathize with the homeless" },
  { n: 30, facet: "C6", keyed: "-", text: "Jump into things without thinking" },
  { n: 31, facet: "N1", keyed: "+", text: "Fear for the worst" },
  { n: 32, facet: "E1", keyed: "+", text: "Feel comfortable around people" },
  { n: 33, facet: "O1", keyed: "+", text: "Enjoy wild flights of fantasy" },
  { n: 34, facet: "A1", keyed: "+", text: "Believe that others have good intentions" },
  { n: 35, facet: "C1", keyed: "+", text: "Excel in what I do" },
  { n: 36, facet: "N2", keyed: "+", text: "Get irritated easily" },
  { n: 37, facet: "E2", keyed: "+", text: "Talk to a lot of different people at parties" },
  { n: 38, facet: "O2", keyed: "+", text: "See beauty in things that others might not notice" },
  { n: 39, facet: "A2", keyed: "-", text: "Cheat to get ahead" },
  { n: 40, facet: "C2", keyed: "-", text: "Often forget to put things back in their proper place" },
  { n: 41, facet: "N3", keyed: "+", text: "Dislike myself" },
  { n: 42, facet: "E3", keyed: "+", text: "Try to lead others" },
  { n: 43, facet: "O3", keyed: "+", text: "Feel others' emotions" },
  { n: 44, facet: "A3", keyed: "+", text: "Am concerned about others" },
  { n: 45, facet: "C3", keyed: "+", text: "Tell the truth" },
  { n: 46, facet: "N4", keyed: "+", text: "Am afraid to draw attention to myself" },
  { n: 47, facet: "E4", keyed: "+", text: "Am always on the go" },
  { n: 48, facet: "O4", keyed: "-", text: "Prefer to stick with things that I know" },
  { n: 49, facet: "A4", keyed: "-", text: "Yell at people" },
  { n: 50, facet: "C4", keyed: "+", text: "Do more than what's expected of me" },
  { n: 51, facet: "N5", keyed: "-", text: "Rarely overindulge" },
  { n: 52, facet: "E5", keyed: "+", text: "Seek adventure" },
  { n: 53, facet: "O5", keyed: "-", text: "Avoid philosophical discussions" },
  { n: 54, facet: "A5", keyed: "-", text: "Think highly of myself" },
  { n: 55, facet: "C5", keyed: "+", text: "Carry out my plans" },
  { n: 56, facet: "N6", keyed: "+", text: "Become overwhelmed by events" },
  { n: 57, facet: "E6", keyed: "+", text: "Have a lot of fun" },
  { n: 58, facet: "O6", keyed: "+", text: "Believe that there is no absolute right or wrong" },
  { n: 59, facet: "A6", keyed: "+", text: "Feel sympathy for those who are worse off than myself" },
  { n: 60, facet: "C6", keyed: "-", text: "Make rash decisions" },
  { n: 61, facet: "N1", keyed: "+", text: "Am afraid of many things" },
  { n: 62, facet: "E1", keyed: "-", text: "Avoid contacts with others" },
  { n: 63, facet: "O1", keyed: "+", text: "Love to daydream" },
  { n: 64, facet: "A1", keyed: "+", text: "Trust what people say" },
  { n: 65, facet: "C1", keyed: "+", text: "Handle tasks smoothly" },
  { n: 66, facet: "N2", keyed: "+", text: "Lose my temper" },
  { n: 67, facet: "E2", keyed: "-", text: "Prefer to be alone" },
  { n: 68, facet: "O2", keyed: "-", text: "Do not like poetry" },
  { n: 69, facet: "A2", keyed: "-", text: "Take advantage of others" },
  { n: 70, facet: "C2", keyed: "-", text: "Leave a mess in my room" },
  { n: 71, facet: "N3", keyed: "+", text: "Am often down in the dumps" },
  { n: 72, facet: "E3", keyed: "+", text: "Take control of things" },
  { n: 73, facet: "O3", keyed: "-", text: "Rarely notice my emotional reactions" },
  { n: 74, facet: "A3", keyed: "-", text: "Am indifferent to the feelings of others" },
  { n: 75, facet: "C3", keyed: "-", text: "Break rules" },
  { n: 76, facet: "N4", keyed: "+", text: "Only feel comfortable with friends" },
  { n: 77, facet: "E4", keyed: "+", text: "Do a lot in my spare time" },
  { n: 78, facet: "O4", keyed: "-", text: "Dislike changes" },
  { n: 79, facet: "A4", keyed: "-", text: "Insult people" },
  { n: 80, facet: "C4", keyed: "-", text: "Do just enough work to get by" },
  { n: 81, facet: "N5", keyed: "-", text: "Easily resist temptations" },
  { n: 82, facet: "E5", keyed: "+", text: "Enjoy being reckless" },
  { n: 83, facet: "O5", keyed: "-", text: "Have difficulty understanding abstract ideas" },
  { n: 84, facet: "A5", keyed: "-", text: "Have a high opinion of myself" },
  { n: 85, facet: "C5", keyed: "-", text: "Waste my time" },
  { n: 86, facet: "N6", keyed: "+", text: "Feel that I'm unable to deal with things" },
  { n: 87, facet: "E6", keyed: "+", text: "Love life" },
  { n: 88, facet: "O6", keyed: "-", text: "Tend to vote for conservative political candidates" },
  { n: 89, facet: "A6", keyed: "-", text: "Am not interested in other people's problems" },
  { n: 90, facet: "C6", keyed: "-", text: "Rush into things" },
  { n: 91, facet: "N1", keyed: "+", text: "Get stressed out easily" },
  { n: 92, facet: "E1", keyed: "-", text: "Keep others at a distance" },
  { n: 93, facet: "O1", keyed: "+", text: "Like to get lost in thought" },
  { n: 94, facet: "A1", keyed: "-", text: "Distrust people" },
  { n: 95, facet: "C1", keyed: "+", text: "Know how to get things done" },
  { n: 96, facet: "N2", keyed: "-", text: "Am not easily annoyed" },
  { n: 97, facet: "E2", keyed: "-", text: "Avoid crowds" },
  { n: 98, facet: "O2", keyed: "-", text: "Do not enjoy going to art museums" },
  { n: 99, facet: "A2", keyed: "-", text: "Obstruct others' plans" },
  { n: 100, facet: "C2", keyed: "-", text: "Leave my belongings around" },
  { n: 101, facet: "N3", keyed: "-", text: "Feel comfortable with myself" },
  { n: 102, facet: "E3", keyed: "-", text: "Wait for others to lead the way" },
  { n: 103, facet: "O3", keyed: "-", text: "Don't understand people who get emotional" },
  { n: 104, facet: "A3", keyed: "-", text: "Take no time for others" },
  { n: 105, facet: "C3", keyed: "-", text: "Break my promises" },
  { n: 106, facet: "N4", keyed: "-", text: "Am not bothered by difficult social situations" },
  { n: 107, facet: "E4", keyed: "-", text: "Like to take it easy" },
  { n: 108, facet: "O4", keyed: "-", text: "Am attached to conventional ways" },
  { n: 109, facet: "A4", keyed: "-", text: "Get back at others" },
  { n: 110, facet: "C4", keyed: "-", text: "Put little time and effort into my work" },
  { n: 111, facet: "N5", keyed: "-", text: "Am able to control my cravings" },
  { n: 112, facet: "E5", keyed: "+", text: "Act wild and crazy" },
  { n: 113, facet: "O5", keyed: "-", text: "Am not interested in theoretical discussions" },
  { n: 114, facet: "A5", keyed: "-", text: "Boast about my virtues" },
  { n: 115, facet: "C5", keyed: "-", text: "Have difficulty starting tasks" },
  { n: 116, facet: "N6", keyed: "-", text: "Remain calm under pressure" },
  { n: 117, facet: "E6", keyed: "+", text: "Look at the bright side of life" },
  { n: 118, facet: "O6", keyed: "-", text: "Believe that we should be tough on crime" },
  { n: 119, facet: "A6", keyed: "-", text: "Try not to think about the needy" },
  { n: 120, facet: "C6", keyed: "-", text: "Act without thinking" },
];

export const ONET_ITEMS: readonly OnetItem[] = [
  { n: 1, area: "R", text: "Build kitchen cabinets" },
  { n: 2, area: "S", text: "Teach an individual an exercise routine" },
  { n: 3, area: "E", text: "Buy and sell stocks and bonds" },
  { n: 4, area: "E", text: "Manage a retail store" },
  { n: 5, area: "C", text: "Develop a spreadsheet using computer software" },
  { n: 6, area: "C", text: "Proofread records or forms" },
  { n: 7, area: "R", text: "Lay brick or tile" },
  { n: 8, area: "S", text: "Help people with personal or emotional problems" },
  { n: 9, area: "E", text: "Operate a beauty salon or barber shop" },
  { n: 10, area: "R", text: "Repair household appliances" },
  { n: 11, area: "I", text: "Develop a new medicine" },
  { n: 12, area: "A", text: "Write books or plays" },
  { n: 13, area: "A", text: "Play a musical instrument" },
  { n: 14, area: "C", text: "Install software across computers on a large network" },
  { n: 15, area: "I", text: "Study ways to reduce water pollution" },
  { n: 16, area: "S", text: "Give career guidance to people" },
  { n: 17, area: "R", text: "Raise fish in a fish hatchery" },
  { n: 18, area: "A", text: "Compose or arrange music" },
  { n: 19, area: "C", text: "Operate a calculator" },
  { n: 20, area: "R", text: "Assemble electronic parts" },
  { n: 21, area: "R", text: "Drive a truck to deliver packages to offices and homes" },
  { n: 22, area: "S", text: "Perform rehabilitation therapy" },
  { n: 23, area: "S", text: "Do volunteer work at a non-profit organization" },
  { n: 24, area: "I", text: "Conduct chemical experiments" },
  { n: 25, area: "A", text: "Draw pictures" },
  { n: 26, area: "S", text: "Teach children how to play sports" },
  { n: 27, area: "A", text: "Create special effects for movies" },
  { n: 28, area: "S", text: "Teach sign language to people who are deaf or hard of hearing" },
  { n: 29, area: "E", text: "Manage a department within a large company" },
  { n: 30, area: "C", text: "Keep shipping and receiving records" },
  { n: 31, area: "I", text: "Study the movement of planets" },
  { n: 32, area: "S", text: "Help conduct a group therapy session" },
  { n: 33, area: "C", text: "Calculate the wages of employees" },
  { n: 34, area: "I", text: "Examine blood samples using a microscope" },
  { n: 35, area: "I", text: "Investigate the cause of a fire" },
  { n: 36, area: "A", text: "Paint sets for plays" },
  { n: 37, area: "E", text: "Start your own business" },
  { n: 38, area: "E", text: "Negotiate business contracts" },
  { n: 39, area: "C", text: "Inventory supplies using a hand-held computer" },
  { n: 40, area: "E", text: "Represent a client in a lawsuit" },
  { n: 41, area: "I", text: "Develop a way to better predict the weather" },
  { n: 42, area: "I", text: "Work in a biology lab" },
  { n: 43, area: "A", text: "Write scripts for movies or television shows" },
  { n: 44, area: "E", text: "Market a new line of clothing" },
  { n: 45, area: "R", text: "Test the quality of parts before shipment" },
  { n: 46, area: "I", text: "Invent a replacement for sugar" },
  { n: 47, area: "A", text: "Perform jazz or tap dance" },
  { n: 48, area: "S", text: "Take care of children at a day-care center" },
  { n: 49, area: "E", text: "Sell merchandise at a department store" },
  { n: 50, area: "C", text: "Record rent payments" },
  { n: 51, area: "R", text: "Repair and install locks" },
  { n: 52, area: "A", text: "Sing in a band" },
  { n: 53, area: "E", text: "Manage a clothing store" },
  { n: 54, area: "C", text: "Keep inventory records" },
  { n: 55, area: "R", text: "Set up and operate machines to make products" },
  { n: 56, area: "R", text: "Put out forest fires" },
  { n: 57, area: "I", text: "Do laboratory tests to identify diseases" },
  { n: 58, area: "A", text: "Edit movies" },
  { n: 59, area: "S", text: "Teach a high-school class" },
  { n: 60, area: "C", text: "Stamp, sort, and distribute mail for an organization" },
];
